Repository OpenVoiceOS/ovos-core, pull requests merged in 2022-09, with the labels that each got.

#192 Cast available langauges set to list for JSON compat.
  mycroft/audio/service.py
  mycroft/listener/service.py
Labels: bug-ovos

#193 Add mobile extension to gui interface for mobile gui app
  mycroft/gui/extensions.py
  mycroft/gui/interfaces/mobile.py
Labels: enhancement

#196 fix/file_watcher_callback
  mycroft/util/file_utils.py
Labels: bug, bug-ovos

#198 Hotwords init bug fixes
  mycroft/listener/__init__.py
Labels: bug

#195 fix/listen_sound
  mycroft/listener/mic.py
Labels: bug, bug-ovos

#200 fix the message sent to the protocol for send_event
  mycroft/gui/namespace.py
  test/unittests/gui/test_namespace_manager.py
Labels: bug
