Repository OpenVoiceOS/ovos-core, pull requests merged in 2022-05, with the labels that each got.

#116 refactor/relax_deps
  requirements/extra-PHAL.txt
  requirements/extra-audiobackend.txt
  requirements/extra-deprecated.txt
  requirements/extra-mark1.txt
  requirements/extra-skills-lgpl.txt
  requirements/extra-skills.txt
  requirements/extra-stt.txt
  requirements/extra-tts.txt
  requirements/minimal.txt
  requirements/requirements.txt
  test/license_tests.py
Labels: packaging

#117 fix/handle bad VAD plugin
  mycroft/listener/mic.py
Labels: bug, bug-ovos

#118 remove pyee, version pinned by bus client directly
  requirements/minimal.txt
  requirements/requirements.txt
Labels: packaging

#119 add automation/docker
  .github/workflows/publish_docker.yml
  Dockerfile
  docker-compose.yml
Labels: tests and automation

#120 refactor/no_adapt
  mycroft/__init__.py
  mycroft/skills/intent_service_interface.py
  mycroft/skills/intent_services/adapt_service.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  requirements/requirements.txt
Labels: refactor, packaging

#121 bump/ovos_utils
  mycroft/__init__.py
  mycroft/skills/intent_service_interface.py
  mycroft/skills/intent_services/adapt_service.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  requirements/minimal.txt
  requirements/requirements.txt
Labels: refactor, packaging

#122 missing requirement - pyyaml
  requirements/extra-skills-lgpl.txt
  requirements/extra-skills.txt
Labels: packaging

#125 fix/LF_unsupported_lang
  mycroft/skills/intent_service.py
Labels: bug

#124 fix/converse_get_response
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/unittests/skills/test_mycroft_skill_get_response.py
Labels: bug, bug-ovos
