Repository OpenVoiceOS/ovos-core, pull requests merged in 2022-10, with the labels that each got.

#203 Fix UI buttons vertical screen issues in developer settings
  mycroft/res/ui/settings/configuration_groups_display.qml
  mycroft/res/ui/settings/developer_settings.qml
Labels: bug, bug-ovos

#201 refactor/selene_api -> ovos-backend-client
  mycroft/__init__.py
  mycroft/api/__init__.py
  mycroft/configuration/mycroft.conf
  mycroft/deprecated/api.py
  mycroft/deprecated/enclosure/mark1/__init__.py
  mycroft/deprecated/skills/__init__.py
  mycroft/deprecated/skills/settings.py
  mycroft/gui/extensions.py
  mycroft/identity/__init__.py
  mycroft/listener/mic.py
  mycroft/listener/service.py
  mycroft/metrics/__init__.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/settings.py
  mycroft/skills/skill_manager.py
  mycroft/skills/skill_updater.py
  requirements/minimal.txt
  requirements/requirements.txt
  test/integrationtests/test_selene_api.py
  test/unittests/util/test_xdg.py
Labels: enhancement

#204 feat/lf_ask_yeno
  mycroft/skills/mycroft_skill/mycroft_skill.py
  requirements/minimal.txt
  requirements/requirements.txt
  test/unittests/skills/test_mycroft_skill_get_response.py
Labels: enhancement

#206 Update ovos_utils.config imports to ovos_config
  mycroft/configuration/__init__.py
  mycroft/configuration/ovos.py
  mycroft/deprecated/enclosure/mark1/__init__.py
  mycroft/deprecated/skills/msm_wrapper.py
  mycroft/deprecated/skills/settings.py
  mycroft/filesystem/__init__.py
  mycroft/listener/mic.py
  mycroft/lock/__init__.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_data.py
  mycroft/skills/skill_loader.py
  mycroft/util/file_utils.py
  requirements/extra-stt.txt
  test/unittests/lock/test_lock.py
  test/unittests/util/test_xdg.py
Labels: refactor

#207 fix/ww_cfg
  mycroft/configuration/mycroft.conf
  mycroft/listener/__init__.py
Labels: bug, bug-ovos

#208 Remove priority skills from default config (inherited from Mycroft)
  mycroft/configuration/mycroft.conf
Labels: bug

#205 fix/pairing_check_again
  mycroft/skills/skill_manager.py
Labels: bug, bug-ovos

#209 fix backend tests
  mycroft/configuration/mycroft.conf
  mycroft/deprecated/skills/settings.py
  test/integrationtests/test_selene_api.py
Labels: bug

#211 feat/error_sound
  mycroft/configuration/mycroft.conf
  mycroft/listener/mic.py
  mycroft/listener/service.py
  mycroft/res/snd/error.mp3
  mycroft/skills/intent_service.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/util/audio_utils.py
Labels: enhancement

#213 fix/backwards_compat
  mycroft/configuration/config.py
Labels: bug, bug-ovos

#214 refactor/update_readme
  README.md
Labels: documentation

#215 change ssh events in ssh gui drop down
  mycroft/res/ui/settings/ssh_settings.qml
Labels: bug

#218 feat/new license workflow
  .github/workflows/license_tests.yml
Labels: tests and automation

#219 bump ovos workshop
  mycroft/dialog/dialog.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_data.py
  requirements/extra-skills-lgpl.txt
  requirements/extra-skills.txt
  requirements/minimal.txt
  requirements/requirements.txt
  test/integrationtests/test_workshop.py
  test/license_tests.py
Labels: refactor, packaging

#221 reviewed german qml translation
  mycroft/res/text/de-de/noise_words.list
  mycroft/res/ui/translations/SmartSpeakerExtension.GuiInterface_de.qm
  mycroft/res/ui/translations/about_page_de.ts
  mycroft/res/ui/translations/configuration_generator_display_de.ts
  mycroft/res/ui/translations/configuration_groups_display_de.ts
  mycroft/res/ui/translations/customize_settings_de.ts
  mycroft/res/ui/translations/customize_theme_de.ts
  mycroft/res/ui/translations/developer_settings_de.ts
  mycroft/res/ui/translations/display_settings_de.ts
  mycroft/res/ui/translations/homescreen_settings_de.ts
  mycroft/res/ui/translations/settingListBox_de.ts
  mycroft/res/ui/translations/settingspage_de.ts
  mycroft/res/ui/translations/ssh_settings_de.ts
Labels: enhancement, hacktoberfest-accepted

#222 shared code from ovos_utils
  mycroft/deprecated/skills/__init__.py
  mycroft/metrics/__init__.py
  mycroft/skills/event_scheduler.py
  mycroft/skills/mycroft_skill/__init__.py
  mycroft/skills/mycroft_skill/event_container.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  requirements/extra-skills-lgpl.txt
  requirements/extra-skills.txt
  requirements/minimal.txt
  requirements/requirements.txt
  test/unittests/skills/test_event_container.py
Labels: refactor

#223 Add ovos_workshop dependency for MycroftSkill imports
  requirements/minimal.txt
Labels: bug, packaging

#224 refactor SkillGUI class to import from ovos_utils
  mycroft/gui/__init__.py
  requirements/minimal.txt
  requirements/requirements.txt
Labels: refactor

#225 fix/reload mid tts/stt
  mycroft/audio/service.py
  mycroft/listener/__init__.py
Labels: bug
