Repository OpenVoiceOS/ovos-core, pull requests merged in 2022-04, with the labels that each got.

#102 Add is_alive service check support to GUI Service
  mycroft/gui/service.py
Labels: bug

#103 fix/remove skill updater lock
  mycroft/skills/skill_updater.py
Labels: bug, bug-ovos

#104 fix/skill settings using wrong xdg path
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: bug, bug-ovos

#107 remove skill settings bad migration path
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: bug, bug-ovos

#108 py3.10 compat
  .github/workflows/unit_tests.yml
  mycroft/client/speech/__main__.py
  mycroft/configuration/mycroft.conf
  mycroft/listener/__init__.py
  mycroft/listener/__main__.py
  requirements/extra-deprecated.txt
  requirements/extra-stt.txt
  requirements/requirements.txt
  requirements/tests.txt
  setup.py
Labels: bug, bug-ovos, packaging

#110 Fix/plugins shutdown
  mycroft/skills/__main__.py
  mycroft/skills/skill_manager.py
Labels: bug

#109 fix/audio service duplicate code
  mycroft/audio/audioservice.py
  mycroft/deprecated/audio/__init__.py
  requirements/minimal.txt
  requirements/requirements.txt
  test/unittests/audio/services/failing/__init__.py
  test/unittests/audio/services/working/__init__.py
  test/unittests/audio/test_service.py
  test/unittests/compat/test_simple_audio_backend.py
Labels: refactor

#113 refactor/default_offline
  README.md
  mycroft/api/__init__.py
  mycroft/configuration/mycroft.conf
  requirements/extra-stt.txt
  requirements/requirements.txt
  start-mycroft.sh
  test/unittests/api/test_api.py
  test/unittests/configuration/test_configuration.py
  test/unittests/skills/test_settings.py
Labels: documentation, enhancement
