Repository OpenVoiceOS/ovos-core, pull requests merged in 2022-08, with the labels that each got.

#182 refactor/gui_cleanup
  mycroft/gui/bus.py
  mycroft/gui/namespace.py
  mycroft/gui/service.py
Labels: bug, refactor, bug-ovos

#183 refactor/padacioso
  mycroft/configuration/mycroft.conf
  mycroft/skills/intent_service_interface.py
  mycroft/skills/intent_services/padatious_service.py
  requirements/extra-skills-lgpl.txt
  requirements/extra-skills.txt
  test/unittests/skills/test_intent_service_interface.py
  test/unittests/skills/test_utterance_intents.py
Labels: enhancement, refactor

#184 feat/integration_tests
  .github/workflows/unit_tests.yml
  test/integrationtests/ovos_tskill_abort/__init__.py
  test/integrationtests/ovos_tskill_abort/locale/en-us/question.dialog
  test/integrationtests/ovos_tskill_abort/locale/en-us/test.intent
  test/integrationtests/ovos_tskill_abort/locale/en-us/test2.intent
  test/integrationtests/ovos_tskill_abort/locale/en-us/test3.intent
  test/integrationtests/ovos_tskill_abort/readme.md
  test/integrationtests/ovos_tskill_abort/setup.py
  test/integrationtests/test_workshop.py
Labels: tests and automation

#176 Bump dependencies to non-alpha versions
  requirements/extra-PHAL.txt
  requirements/extra-audiobackend.txt
  requirements/extra-skills-lgpl.txt
  requirements/extra-skills.txt
  requirements/minimal.txt
  requirements/requirements.txt
  test/license_tests.py
Labels: packaging

#188 feat/common_query_tests
  .github/workflows/unit_tests.yml
  mycroft/skills/intent_services/commonqa_service.py
  test/unittests/common_query/ovos_tskill_fakewiki/__init__.py
  test/unittests/common_query/ovos_tskill_fakewiki/locale/en-us/More.voc
  test/unittests/common_query/ovos_tskill_fakewiki/locale/en-us/no_answer.dialog
  test/unittests/common_query/ovos_tskill_fakewiki/locale/en-us/search_fakewiki.intent
  test/unittests/common_query/ovos_tskill_fakewiki/setup.py
  test/unittests/common_query/test_common_query.py
  test/unittests/common_query/test_continuous_dialog.py
  test/unittests/common_query/test_skill.py
Labels: tests and automation

#150 feat/listening_modes
  mycroft/configuration/mycroft.conf
  mycroft/listener/__init__.py
  mycroft/listener/mic.py
  mycroft/listener/service.py
  mycroft/listener/silence.py
Labels: enhancement
