Repository OpenVoiceOS/ovos-core, pull requests merged in 2022-06, with the labels that each got.

#105 refactor/improve_config
  mycroft/__init__.py
  mycroft/api/__init__.py
  mycroft/audio/audioservice.py
  mycroft/audio/speech.py
  mycroft/audio/tts.py
  mycroft/configuration/config.py
  mycroft/configuration/locale.py
  mycroft/deprecated/enclosure/base.py
  mycroft/deprecated/enclosure/main.py
  mycroft/dialog/dialog.py
  mycroft/gui/__init__.py
  mycroft/gui/bus.py
  mycroft/gui/extensions.py
  mycroft/gui/homescreen.py
  mycroft/gui/namespace.py
  mycroft/listener/__init__.py
  mycroft/listener/hotword_factory.py
  mycroft/listener/mic.py
  mycroft/listener/service.py
  mycroft/listener/stt.py
  mycroft/messagebus/client/client.py
  mycroft/messagebus/load_config.py
  mycroft/messagebus/send_func.py
  mycroft/metrics/__init__.py
  mycroft/res/text/en-us/configurations.json
  mycroft/session/__init__.py
  mycroft/skills/event_scheduler.py
  mycroft/skills/intent_service.py
  mycroft/skills/intent_services/adapt_service.py
  mycroft/skills/intent_services/converse_service.py
  mycroft/skills/intent_services/padatious_service.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/settings.py
  mycroft/skills/skill_loader.py
  mycroft/skills/skill_manager.py
  mycroft/skills/skill_updater.py
  mycroft/util/audio_test.py
  mycroft/util/audio_utils.py
  mycroft/util/file_utils.py
  mycroft/util/format.py
  mycroft/util/network_utils.py
  mycroft/util/parse.py
  mycroft/util/process_utils.py
  mycroft/util/time.py
  mycroft/version.py
  requirements/minimal.txt
  requirements/requirements.txt
  test/unittests/api/test_api.py
  test/unittests/base.py
  test/unittests/configuration/test_configuration.py
  test/unittests/messagebus/client/test_client.py
  test/unittests/skills/test_intent_service.py
  test/unittests/skills/test_mycroft_skill.py
  test/unittests/skills/test_skill_loader.py
  test/unittests/skills/test_skill_manager.py
  test/unittests/stt/test_stt.py
  test/unittests/util/test_audio_utils.py
  test/unittests/util/test_network_utils.py
  test/unittests/util/test_time.py
Labels: enhancement, refactor

#130 port of the resource file handling refactor from mk2
  mycroft/deprecated/skills.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_data.py
Labels: refactor, mk2

#132 fix/pairing readiness
  mycroft/skills/skill_manager.py
  test/unittests/skills/test_skill_manager.py
Labels: bug, bug-ovos

#131 feat/user resources
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_data.py
Labels: enhancement

#133 fix/filesystem_path
  mycroft/filesystem/__init__.py
  mycroft/identity/__init__.py
  test/unittests/util/test_xdg.py
Labels: bug, bug-ovos

#134 fix/identity_file migration
  mycroft/identity/__init__.py
Labels: bug, bug-ovos

#136 feat/setup_events
  mycroft/skills/skill_manager.py
  test/unittests/skills/test_skill_manager.py
Labels: enhancement

#138 fix/filesystem_path_collision
  mycroft/filesystem/__init__.py
Labels: bug, bug-ovos

#135 Fix/qml resources
  mycroft/gui/__init__.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_data.py
  test/unittests/enclosure/test_gui.py
Labels: bug, refactor, bug-ovos

#140 Add color scheme modes and color scheme custom generator support
  mycroft/gui/interfaces/smartspeaker.py
  mycroft/res/snd/clicked.wav
  mycroft/res/ui/settings/ThemeView.qml
  mycroft/res/ui/settings/code/colorUtils.js
  mycroft/res/ui/settings/customize_settings.qml
  mycroft/res/ui/settings/customize_theme.qml
  mycroft/res/ui/settings/delegates/BrightnessSlider.qml
  mycroft/res/ui/settings/delegates/ColorSelectPrimary.qml
  mycroft/res/ui/settings/delegates/ColorSelectSecondary.qml
  mycroft/res/ui/settings/delegates/ColorSlider.qml
  mycroft/res/ui/settings/delegates/NameSelect.qml
  mycroft/res/ui/settings/delegates/Palette.qml
  mycroft/res/ui/settings/delegates/PalettesGrid.qml
  mycroft/res/ui/settings/delegates/SetNameBox.qml
  mycroft/res/ui/settings/developer_settings.qml
  mycroft/res/ui/settings/homescreen_settings.qml
  mycroft/res/ui/settings/images/next.svg
  mycroft/res/ui/settings/settingspage.qml
  mycroft/res/ui/settings/ssh_settings.qml
Labels: enhancement

#142 fix/config_hotreload
  mycroft/configuration/config.py
Labels: bug, bug-ovos

#141 feat/feat/improve_cq_matching
  mycroft/res/text/en-us/common_play.voc
  mycroft/skills/intent_services/commonqa_service.py
Labels: enhancement

#144 refactor/ready_check_bus_spam
  mycroft/skills/skill_manager.py
Labels: refactor

#143 refactor/skill_reload
  mycroft/skills/skill_loader.py
  mycroft/skills/skill_manager.py
  mycroft/util/file_utils.py
  test/unittests/skills/test_skill_loader.py
  test/unittests/skills/test_skill_manager.py
Labels: refactor

#146 Refactor audio module into service
  mycroft/audio/__main__.py
  mycroft/audio/service.py
  mycroft/audio/speech.py
  mycroft/deprecated/audio/speech.py
  test/unittests/audio/test_speech.py
  test/unittests/compat/test_imports.py
Labels: refactor

#147 hotfix/deprecated_method
  mycroft/deprecated/audio/speech.py
Labels: bug, bug-ovos

#148 Update changelog action
  .github/workflows/publish_alpha.yml
Labels: tests and automation

#149 Add About Page To Additional Settings and SmartSpeaker Extension
  mycroft/gui/interfaces/smartspeaker.py
  mycroft/res/ui/settings/SettingsModel.qml
  mycroft/res/ui/settings/about_page.qml
  mycroft/res/ui/settings/images/info.svg
Labels: enhancement

#154 refactor/native_ocp
  mycroft/audio/audioservice.py
  mycroft/configuration/mycroft.conf
Labels: refactor

#155 fix/skill_settings_callback
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/util/file_utils.py
Labels: bug, bug-ovos

#161 Resolve occasional config init bug
  mycroft/configuration/config.py
Labels: bug, bug-ovos

#152 feat/speak_error_flag
  mycroft/skills/common_iot_skill.py
  mycroft/skills/common_play_skill.py
  mycroft/skills/common_query_skill.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  requirements/extra-skills-lgpl.txt
  requirements/extra-skills.txt
  requirements/requirements.txt
  test/unittests/skills/test_skill_api.py
Labels: bug, enhancement

#151 refactor/rename_audiospeech_services
  mycroft/audio/__main__.py
  mycroft/audio/service.py
  mycroft/client/speech/__main__.py
  mycroft/listener/__main__.py
  mycroft/listener/service.py
  test/unittests/audio/test_speech.py
Labels: refactor, breaking
