Repository OpenVoiceOS/ovos-core, pull requests merged in 2022-02, with the labels that each got.

#25 refactor/goodbye_msm
  mycroft/configuration/mycroft.conf
  mycroft/skills/__main__.py
  mycroft/skills/audioservice.py
  mycroft/skills/msm_wrapper.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/settings.py
  mycroft/skills/skill_loader.py
  mycroft/skills/skill_manager.py
  mycroft/skills/skill_updater.py
  requirements/extra-mycroft.txt
  requirements/extra-skills-minimal.txt
  requirements/extra-skills.txt
  requirements/minimal.txt
  test/unittests/base.py
  test/unittests/mocks.py
  test/unittests/skills/test_settings.py
  test/unittests/skills/test_skill_manager.py
  test/unittests/skills/test_skill_updater.py
Labels: refactor

#27 Refactor/ simplify skill loading
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_loader.py
Labels: refactor

#32 Refactor/converse
  mycroft/skills/intent_service.py
  mycroft/skills/intent_services/__init__.py
  mycroft/skills/intent_services/converse_service.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_manager.py
Labels: enhancement, refactor

#11 refactor/settings
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/settings.py
Labels: refactor

#28 Refactor/standardize skill id usage
  mycroft/skills/event_scheduler.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: refactor

#9 Feat/skill plugins
  mycroft/skills/skill_loader.py
  mycroft/skills/skill_manager.py
Labels: enhancement, neon-core

#48 fix/log config
  mycroft/__init__.py
Labels: bug-ovos

#47 fix/speech
  mycroft/audio/speech.py
  requirements/minimal.txt
  requirements/requirements.txt
Labels: bug-ovos

#46 feat/PHAL
  mycroft/client/enclosure/__main__.py
  requirements/extra-PHAL.txt
  requirements/requirements.txt
  setup.py
Labels: enhancement

#54 feat/license tests workflow
  .github/workflows/license_tests.yml
  test/license_tests.py
Labels: tests and automation

#52 bump requests to avoid GPL transient dependency
  requirements/minimal.txt
  requirements/requirements.txt
Labels: refactor

#53 Refactor/remove pyxdg
  mycroft/client/enclosure/mark1/__init__.py
  mycroft/client/text/text_client.py
  mycroft/configuration/config.py
  mycroft/configuration/locations.py
  mycroft/filesystem/__init__.py
  mycroft/skills/event_scheduler.py
  mycroft/skills/msm_wrapper.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/settings.py
  mycroft/skills/skill_loader.py
  mycroft/skills/skill_updater.py
  mycroft/util/file_utils.py
  requirements/minimal.txt
  requirements/requirements.txt
Labels: refactor

#55 fix/skill_settings backwards compat
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: bug-ovos

#61 Fix/adapt lang missing
  .github/workflows/license_tests.yml
  .github/workflows/unit_tests.yml
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/settings.py
  test/unittests/skills/test_mycroft_skill.py
  test/unittests/skills/test_mycroft_skill_get_response.py
  test/unittests/skills/test_settings.py
Labels: bug-ovos

#63 bump/non_alpha_opm+utils
  .github/workflows/build_tests.yml
  requirements/minimal.txt
  requirements/requirements.txt
Labels: refactor

#69 Tests/port template workflows
  .github/workflows/build_tests.yml
  .github/workflows/dev2master.yml
  .github/workflows/license_tests.yml
  .github/workflows/publish_alpha.yml
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
  .github/workflows/publish_test_build.yml
  .github/workflows/unit_tests.yml
  LICENSE
  MANIFEST.in
  mycroft/version.py
  scripts/bump_alpha.py
  scripts/bump_build.py
  scripts/bump_major.py
  scripts/bump_minor.py
  setup.py
Labels: tests and automation

#67 Refactor/skill process status
  mycroft/skills/__main__.py
  mycroft/skills/skill_manager.py
  test/unittests/skills/test_skill_manager.py
Labels: refactor

#70 Fix/changelog text
  .github/workflows/publish_alpha.yml
Labels: tests and automation

#71 Fix/unify converse namespace
  mycroft/skills/intent_services/converse_service.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: bug, bug-ovos

#72 Fix/update workflows
  .github/workflows/build_tests.yml
  .github/workflows/publish_alpha.yml
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
  .github/workflows/unit_tests.yml
  scripts/remove_alpha.py
Labels: tests and automation
