Repository OpenVoiceOS/ovos-core, pull requests merged in 2022-07, with the labels that each got.

#167 refactor/ovos_config_pkg
  mycroft/configuration/__init__.py
  mycroft/configuration/config.py
  mycroft/configuration/locale.py
  mycroft/configuration/locations.py
  requirements/minimal.txt
  requirements/requirements.txt
  test/unittests/configuration/test_configuration.py
Labels: refactor, packaging

#169 fix/hotword reload
  mycroft/listener/mic.py
Labels: bug

#170 Handle recursive inspection of resource directories
  mycroft/skills/skill_data.py
Labels: bug

#173 Prevent duplicate language intent registration
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/unittests/skills/test_mycroft_skill.py
Labels: bug, bug-ovos

#178 Update references to `ovos_config`
  mycroft/__init__.py
  mycroft/api/__init__.py
  mycroft/audio/__main__.py
  mycroft/audio/audioservice.py
  mycroft/audio/service.py
  mycroft/audio/tts.py
  mycroft/client/speech/__main__.py
  mycroft/deprecated/enclosure/base.py
  mycroft/deprecated/enclosure/main.py
  mycroft/deprecated/enclosure/mark1/__init__.py
  mycroft/dialog/dialog.py
  mycroft/gui/__init__.py
  mycroft/gui/__main__.py
  mycroft/gui/bus.py
  mycroft/gui/extensions.py
  mycroft/gui/homescreen.py
  mycroft/gui/namespace.py
  mycroft/gui/service.py
  mycroft/listener/__init__.py
  mycroft/listener/__main__.py
  mycroft/listener/hotword_factory.py
  mycroft/listener/mic.py
  mycroft/listener/service.py
  mycroft/listener/stt.py
  mycroft/messagebus/load_config.py
  mycroft/messagebus/send_func.py
  mycroft/metrics/__init__.py
  mycroft/session/__init__.py
  mycroft/skills/__main__.py
  mycroft/skills/common_query_skill.py
  mycroft/skills/event_scheduler.py
  mycroft/skills/intent_service.py
  mycroft/skills/intent_services/adapt_service.py
  mycroft/skills/intent_services/converse_service.py
  mycroft/skills/intent_services/padatious_service.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/settings.py
  mycroft/skills/skill_loader.py
  mycroft/skills/skill_manager.py
  mycroft/skills/skill_updater.py
  mycroft/util/audio_test.py
  mycroft/util/audio_utils.py
  mycroft/util/file_utils.py
  mycroft/util/format.py
  mycroft/util/network_utils.py
  mycroft/util/parse.py
  mycroft/util/process_utils.py
  mycroft/util/time.py
  test/unittests/util/test_audio_utils.py
  test/unittests/util/test_network_utils.py
Labels: refactor

#179 refactor/native_sources
  mycroft/audio/audioservice.py
  mycroft/audio/service.py
  mycroft/configuration/mycroft.conf
Labels: enhancement

#180 feat/queue_audio
  mycroft/audio/service.py
Labels: enhancement
