Repository OpenVoiceOS/ovos-core, pull requests merged in 2022-03, with the labels that each got.

#73 Add GUI Extensions Support
  mycroft/configuration/mycroft.conf
  mycroft/gui/extensions.py
  mycroft/gui/homescreen.py
  mycroft/gui/namespace.py
  mycroft/gui/service.py
  test/unittests/gui/test_bigscreen_extension.py
  test/unittests/gui/test_extensions_manager.py
  test/unittests/gui/test_smartspeaker_extension.py
Labels: enhancement

#77 feat/fallback_stt
  .github/workflows/unit_tests.yml
  mycroft/client/speech/listener.py
  mycroft/configuration/mycroft.conf
  mycroft/stt/__init__.py
  requirements/extra-stt.txt
  requirements/minimal.txt
  requirements/requirements.txt
  test/license_tests.py
  test/unittests/base_plugins.py
  test/unittests/stt/__init__.py
  test/unittests/stt/test_stt.py
Labels: enhancement

#83 matrix chatbot
  .github/workflows/publish_alpha.yml
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
Labels: tests and automation

#82 Rewrite MutableStream class for microphone.
  mycroft/client/speech/listener.py
  mycroft/client/speech/mic.py
Labels: refactor, mycroft-sync, mk2

#86 SmartSpeaker Extension: Add GUI interface for additional settings
  mycroft/gui/extensions.py
  mycroft/gui/interfaces/smartspeaker.py
  mycroft/res/ui/SYSTEM_AdditionalSettings.qml
  mycroft/res/ui/settings/SettingsModel.qml
  mycroft/res/ui/settings/developer_settings.qml
  mycroft/res/ui/settings/homescreen_settings.qml
  mycroft/res/ui/settings/images/back.png
  mycroft/res/ui/settings/images/home.svg
  mycroft/res/ui/settings/images/power.svg
  mycroft/res/ui/settings/images/restart.svg
  mycroft/res/ui/settings/images/settings.png
  mycroft/res/ui/settings/images/ssh.svg
  mycroft/res/ui/settings/images/tick.svg
  mycroft/res/ui/settings/settingspage.qml
  mycroft/res/ui/settings/ssh_settings.qml
Labels: enhancement

#87 deprecate DevicePrimer
  mycroft/skills/__main__.py
Labels: refactor

#88 Fix/ready timeout
  mycroft/skills/skill_manager.py
Labels: bug, bug-ovos

#90 refator/process_utils from ovos_utils
  mycroft/util/process_utils.py
  requirements/minimal.txt
  requirements/requirements.txt
Labels: refactor

#91 fix/double_stt
  mycroft/client/speech/listener.py
Labels: bug, bug-ovos

#92 fix/mycroft_ready
  mycroft/skills/skill_manager.py
Labels: bug, bug-ovos

#93 fix/loop_race_condition
  mycroft/client/speech/service.py
  mycroft/skills/skill_manager.py
  test/unittests/skills/test_skill_manager.py
Labels: bug

#94 monitor all logs
  mycroft/client/text/__main__.py
  mycroft/client/text/text_client.py
Labels: bug

#95 fix/fallback_tts
  mycroft/audio/speech.py
Labels: bug, bug-ovos

#96 Fix/tts logs and shutdown
  mycroft/audio/speech.py
  test/unittests/audio/test_speech.py
Labels: bug, bug-ovos

#98 Fix bug in streaming STT audio stream handling
  mycroft/client/speech/listener.py
  mycroft/client/speech/mic.py
Labels: bug
