Repository OpenVoiceOS/ovos-core, pull requests merged in 2023-10, with the labels that each got.

#358 unittests/fallbackV1
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  requirements/requirements.txt
  test/end2end/session/skill-ovos-fallback-unknownv1/__init__.py
  test/end2end/session/skill-ovos-fallback-unknownv1/locale/en-us/unknown.dialog
  test/end2end/session/skill-ovos-fallback-unknownv1/setup.py
  test/end2end/session/test_complete_failure.py
  test/end2end/session/test_fallback.py
  test/end2end/session/test_fallback_v1.py
  test/end2end/session/test_session.py
Labels: bug, tests and automation

#359 unitests/converse
  .github/workflows/unit_tests.yml
  test/end2end/session/minicroft.py
  test/end2end/session/skill-converse_test/__init__.py
  test/end2end/session/skill-converse_test/locale/en-us/converse_off.intent
  test/end2end/session/skill-converse_test/locale/en-us/converse_on.intent
  test/end2end/session/skill-converse_test/locale/en-us/get.dialog
  test/end2end/session/skill-converse_test/locale/en-us/question.dialog
  test/end2end/session/skill-converse_test/locale/en-us/test.intent
  test/end2end/session/skill-converse_test/locale/en-us/test2.intent
  test/end2end/session/skill-converse_test/locale/en-us/test3.intent
  test/end2end/session/skill-converse_test/locale/en-us/test_get_response.intent
  test/end2end/session/skill-converse_test/setup.py
  test/end2end/session/test_converse.py
Labels: tests and automation

#360 unittests/skill_self_activation
  ovos_core/intent_services/converse_service.py
  test/end2end/session/skill-converse_test/__init__.py
  test/end2end/session/test_converse.py
  test/end2end/session/test_fallback_v1.py
Labels: tests and automation

#361 unittests/get_response
  requirements/requirements.txt
  test/end2end/session/skill-converse_test/__init__.py
  test/end2end/session/test_get_response.py
  test/integrationtests/test_workshop.py
  test/unittests/skills/test_mycroft_skill_get_response.py
Labels: bug, tests and automation

#362 fix/get_response some more
  requirements/requirements.txt
  test/end2end/session/test_get_response.py
  test/unittests/skills/test_mycroft_skill_get_response.py
Labels: bug, tests and automation

#363 unittests/get_response_reprompting
  requirements/requirements.txt
  test/end2end/session/skill-converse_test/__init__.py
  test/end2end/session/skill-converse_test/locale/en-us/test_get_response3.intent
  test/end2end/session/test_get_response.py
Labels: bug, tests and automation

#364 refactor/simplify_session
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/converse_service.py
  requirements/requirements.txt
Labels: refactor, packaging

#365 Delete .github/workflows/publish_docker.yml
  .github/workflows/publish_docker.yml
  Dockerfile
Labels: tests and automation

#367 complete nested test
  test/end2end/session/test_get_response.py
Labels: tests and automation

#366 unittests/get_response_cascade
  test/end2end/session/skill-converse_test/__init__.py
  test/end2end/session/skill-converse_test/locale/en-us/test_get_response_cascade.intent
  test/end2end/session/test_get_response.py
Labels: tests and automation

#369 feat: explicit message response to activate/deactivate skill
  ovos_core/skill_manager.py
  test/unittests/skills/test_skill_manager.py
Labels: enhancement

#372 fix/get_response_not_ponging
  ovos_core/intent_services/converse_service.py
  requirements/requirements.txt
Labels: bug

#371 Refactor/converse messages
  ovos_core/intent_services/converse_service.py
  requirements/requirements.txt
  test/end2end/session/test_complete_failure.py
  test/end2end/session/test_converse.py
  test/end2end/session/test_fallback.py
  test/end2end/session/test_fallback_v1.py
  test/end2end/session/test_get_response.py
  test/end2end/session/test_session.py
  test/integrationtests/test_workshop.py
  test/unittests/common_query/test_skill.py
  test/unittests/skills/test_intent_service.py
Labels: enhancement, refactor

#373 unittests/event_scheduler
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  test/end2end/session/minicroft.py
  test/end2end/session/skill-ovos-schedule/MANIFEST.in
  test/end2end/session/skill-ovos-schedule/__init__.py
  test/end2end/session/skill-ovos-schedule/locale/en-us/dialog/done.dialog
  test/end2end/session/skill-ovos-schedule/locale/en-us/dialog/trigger.dialog
  test/end2end/session/skill-ovos-schedule/locale/en-us/vocab/Schedule.voc
  test/end2end/session/skill-ovos-schedule/setup.py
  test/end2end/session/test_complete_failure.py
  test/end2end/session/test_converse.py
  test/end2end/session/test_fallback.py
  test/end2end/session/test_fallback_v1.py
  test/end2end/session/test_get_response.py
  test/end2end/session/test_sched.py
  test/end2end/session/test_session.py
Labels: tests and automation

#375 fix unittests for ovos-utils==0.0.36a9
  requirements/requirements.txt
  test/unittests/common_query/test_common_query.py
  test/unittests/common_query/test_continuous_dialog.py
Labels: tests and automation

#374 unittests/message_routing
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  requirements/requirements.txt
  test/backwards_compat/__init__.py
  test/backwards_compat/test_imports.py
  test/backwards_compat/test_simple_audio_backend.py
  test/end2end/minicroft.py
  test/end2end/routing/__init__.py
  test/end2end/routing/test_sched.py
  test/end2end/routing/test_session.py
  test/end2end/session/test_complete_failure.py
  test/end2end/session/test_converse.py
  test/end2end/session/test_fallback.py
  test/end2end/session/test_fallback_v1.py
  test/end2end/session/test_get_response.py
  test/end2end/session/test_sched.py
  test/end2end/session/test_session.py
  test/end2end/skill-converse_test/__init__.py
  test/end2end/skill-converse_test/locale/en-us/converse_off.intent
  test/end2end/skill-converse_test/locale/en-us/converse_on.intent
  test/end2end/skill-converse_test/locale/en-us/get.dialog
  test/end2end/skill-converse_test/locale/en-us/question.dialog
  test/end2end/skill-converse_test/locale/en-us/test.intent
  test/end2end/skill-converse_test/locale/en-us/test2.intent
  test/end2end/skill-converse_test/locale/en-us/test3.intent
  test/end2end/skill-converse_test/locale/en-us/test_get_response.intent
  test/end2end/skill-converse_test/locale/en-us/test_get_response3.intent
  test/end2end/skill-converse_test/locale/en-us/test_get_response_cascade.intent
  test/end2end/skill-converse_test/setup.py
  test/end2end/skill-ovos-fallback-unknown/__init__.py
  test/end2end/skill-ovos-fallback-unknown/locale/en-us/unknown.dialog
  test/end2end/skill-ovos-fallback-unknown/setup.py
  test/end2end/skill-ovos-fallback-unknownv1/__init__.py
  test/end2end/skill-ovos-fallback-unknownv1/locale/en-us/unknown.dialog
  test/end2end/skill-ovos-fallback-unknownv1/setup.py
  test/end2end/skill-ovos-hello-world/MANIFEST.in
  test/end2end/skill-ovos-hello-world/__init__.py
  test/end2end/skill-ovos-hello-world/locale/en-us/dialog/hello.world.dialog
  test/end2end/skill-ovos-hello-world/locale/en-us/vocab/HelloWorldKeyword.voc
  test/end2end/skill-ovos-hello-world/setup.py
  test/end2end/skill-ovos-schedule/MANIFEST.in
  test/end2end/skill-ovos-schedule/__init__.py
  test/end2end/skill-ovos-schedule/locale/en-us/dialog/done.dialog
  test/end2end/skill-ovos-schedule/locale/en-us/dialog/trigger.dialog
  test/end2end/skill-ovos-schedule/locale/en-us/vocab/Schedule.voc
  test/end2end/skill-ovos-schedule/setup.py
Labels: bug, tests and automation
