Repository OpenVoiceOS/ovos-core, pull requests merged in 2023-09, with the labels that each got.

#345 refactor/sound_output_in_ovos_audio
  ovos_core/intent_services/__init__.py
Labels: refactor

#347 feat/runtime skill installer
  ovos_core/__main__.py
  ovos_core/skill_installer.py
Labels: enhancement

#350 feat/active skills from Session
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/converse_service.py
  test/unittests/skills/test_intent_service.py
  test/unittests/skills/test_mycroft_skill.py
Labels: enhancement

#352 feat/pipeline_session
  ovos_core/intent_services/__init__.py
  requirements/requirements.txt
Labels: enhancement

#354 default session managed by core
  ovos_core/intent_services/__init__.py
  requirements/requirements.txt
Labels: enhancement

#160 feat/converse_session
  ovos_core/intent_services/converse_service.py
  requirements/requirements.txt
  test/unittests/skills/test_mycroft_skill.py
  test/unittests/skills/test_mycroft_skill_get_response.py
Labels: enhancement

#355 fix/session dropping active_skills
  .github/workflows/unit_tests.yml
  .gitignore
  mycroft/__init__.py
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/converse_service.py
  requirements/requirements.txt
  test/end2end/__init__.py
  test/end2end/session/__init__.py
  test/end2end/session/skill-ovos-hello-world/MANIFEST.in
  test/end2end/session/skill-ovos-hello-world/__init__.py
  test/end2end/session/skill-ovos-hello-world/locale/en-us/dialog/hello.world.dialog
  test/end2end/session/skill-ovos-hello-world/locale/en-us/vocab/HelloWorldKeyword.voc
  test/end2end/session/skill-ovos-hello-world/setup.py
  test/end2end/session/test_session.py
  test/unittests/skills/test_intent_service.py
Labels: bug, tests and automation

#356 add more tests / fix codecov workflow
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  test/end2end/session/test_session.py
Labels: tests and automation

#339 Update ovos-utils and ovos-workshop to latest alpha versions
  requirements/requirements.txt
  test/unittests/skills/test_event_container.py
Labels: tests and automation, packaging

#357 unittests/fallback_service
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  ovos_core/intent_services/fallback_service.py
  requirements/requirements.txt
  test/end2end/session/minicroft.py
  test/end2end/session/skill-ovos-fallback-unknown/__init__.py
  test/end2end/session/skill-ovos-fallback-unknown/locale/en-us/unknown.dialog
  test/end2end/session/skill-ovos-fallback-unknown/setup.py
  test/end2end/session/test_fallback.py
  test/end2end/session/test_session.py
Labels: tests and automation
