Repository OpenVoiceOS/ovos-core, pull requests merged in 2023-05, with the labels that each got.

#316 fix/fallbackV1
  mycroft/skills/intent_services/fallback_service.py
Labels: bug

#309 refactor/padatious_samples
  ovos_core/intent_services/padatious_service.py
Labels: bug

#317 fix version
  .github/workflows/publish_alpha.yml
  .github/workflows/unit_tests.yml
  mycroft/version.py
  ovos_core/version.py
Labels: bug, tests and automation, packaging

#318 fix: import missed in refactor
  mycroft/metrics/__init__.py
Labels: bug

#320 fix/padatious_utt
  ovos_core/intent_services/padatious_service.py
Labels: bug

#321 Implement threaded Padatious intent calculation
  .github/workflows/unit_tests.yml
  ovos_core/intent_services/padatious_service.py
  requirements/requirements.txt
  test/unittests/skills/test_utterance_intents.py
Labels: enhancement

#323 Update `get_skill_directories` import
  ovos_core/skill_manager.py
Labels: bug

#324 Update README.md + rm start/stop
  README.md
Labels: documentation

#325 refactor/skill_settings_change
  mycroft/util/file_utils.py
  ovos_core/skill_manager.py
  requirements/requirements.txt
  start-mycroft.sh
  stop-mycroft.sh
Labels: enhancement
