Repository OpenVoiceOS/ovos-core, pull requests merged in 2023-04, with the labels that each got.

#284 add common_play.voc translations
  mycroft/res/text/ca-es/common_play.voc
  mycroft/res/text/cs-cz/common_play.voc
  mycroft/res/text/da-dk/common_play.voc
  mycroft/res/text/de-de/common_play.voc
  mycroft/res/text/es-es/common_play.voc
  mycroft/res/text/fr-fr/common_play.voc
  mycroft/res/text/hu-hu/common_play.voc
  mycroft/res/text/it-it/common_play.voc
  mycroft/res/text/nl-nl/common_play.voc
  mycroft/res/text/pl-pl/common_play.voc
  mycroft/res/text/pt-pt/common_play.voc
  mycroft/res/text/ru-ru/common_play.voc
  mycroft/res/text/sv-fi/common_play.voc
  mycroft/res/text/sv-se/common_play.voc
  mycroft/res/text/tr-tr/common_play.voc
Labels: translation

#302 fix/common_qa errors
  mycroft/skills/common_query_skill.py
  mycroft/skills/intent_services/commonqa_service.py
  requirements/minimal.txt
  requirements/requirements.txt
  test/unittests/common_query/ovos_tskill_fakewiki/__init__.py
  test/unittests/common_query/test_common_query.py
Labels: bug, refactor

#305 refactor/common_qa_speak
  mycroft/skills/intent_services/commonqa_service.py
Labels: refactor

#306 refactor/skill_loader_from_workshop
  .github/workflows/build_tests.yml
  mycroft/skills/context.py
  mycroft/skills/mycroft_skill/decorators.py
  mycroft/skills/settings.py
  mycroft/skills/skill_loader.py
  mycroft/skills/skill_manager.py
  requirements/minimal.txt
  requirements/requirements.txt
  test/unittests/common_query/test_common_query.py
  test/unittests/skills/test_common_query_skill.py
  test/unittests/skills/test_skill_loader.py
Labels: refactor

#311 bump dependencies
  requirements/extra-tts.txt
  requirements/minimal.txt
  requirements/requirements.txt
  test/unittests/skills/test_intent_service_interface.py
  test/unittests/skills/test_mycroft_skill.py
Labels: bug, packaging

#307 refactor/fallback_skills_v2
  mycroft/skills/intent_services/fallback_service.py
Labels: enhancement, refactor

#314 fix/fallbacks
  mycroft/skills/intent_services/fallback_service.py
  requirements/extra-skills-lgpl.txt
  requirements/extra-skills.txt
  requirements/minimal.txt
  requirements/requirements.txt
  test/unittests/skills/test_fallback_skill.py
Labels: bug

#303 refactor/ovos_listener
  mycroft/client/speech/__init__.py
  mycroft/client/speech/__main__.py
  mycroft/client/speech/data_structures.py
  mycroft/client/speech/hotword_factory.py
  mycroft/client/speech/listener.py
  mycroft/client/speech/mic.py
  mycroft/client/speech/service.py
  mycroft/client/speech/silence.py
  mycroft/deprecated/stt.py
  mycroft/listener/__init__.py
  mycroft/listener/__main__.py
  mycroft/listener/data_structures.py
  mycroft/listener/hotword_factory.py
  mycroft/listener/mic.py
  mycroft/listener/service.py
  mycroft/listener/silence.py
  mycroft/listener/stt.py
  requirements/extra-stt.txt
  requirements/requirements.txt
  test/unittests/client/__init__.py
  test/unittests/client/data/hey_mycroft.wav
  test/unittests/client/data/mycroft.wav
  test/unittests/client/data/mycroft_wakeup.wav
  test/unittests/client/data/record.wav
  test/unittests/client/data/stop.wav
  test/unittests/client/data/weather_mycroft.wav
  test/unittests/client/test_data_structures.py
  test/unittests/client/test_dynamic_energy_test.py
  test/unittests/client/test_hotword_factory.py
  test/unittests/client/test_noise_tracker.py
  test/unittests/stt/__init__.py
  test/unittests/stt/test_stt.py
Labels: refactor, packaging

#304 refactor/ovos_audio
  mycroft/audio/__init__.py
  mycroft/audio/__main__.py
  mycroft/audio/audioservice.py
  mycroft/audio/interface.py
  mycroft/audio/service.py
  mycroft/audio/services/__init__.py
  mycroft/audio/services/simple/__init__.py
  mycroft/audio/speech.py
  mycroft/audio/tts.py
  mycroft/audio/utils.py
  mycroft/deprecated/audio/services/simple/__init__.py
  mycroft/deprecated/audio/services/vlc_player/__init__.py
  mycroft/deprecated/enclosure/mark1/__init__.py
  mycroft/skills/intent_service.py
  mycroft/tts/__init__.py
  mycroft/tts/tts.py
  mycroft/util/__init__.py
  mycroft/util/audio_test.py
  requirements/extra-audiobackend.txt
  requirements/extra-tts.txt
  requirements/requirements.txt
  test/unittests/audio/__init__.py
  test/unittests/audio/services/failing/__init__.py
  test/unittests/audio/services/working/__init__.py
  test/unittests/audio/test_service.py
  test/unittests/audio/test_speech.py
  test/unittests/audio/test_utils.py
Labels: refactor
