Repository OpenVoiceOS/ovos-core, pull requests merged in 2024-01, with the labels that each got.

#395 Deregister any entities when a skill is detached. Fixes #394
  ovos_core/intent_services/padacioso_service.py
Labels: bug

#398 allow alpha versions of ovos-utils
  requirements/requirements.txt
Labels: packaging

#329 CommonQuery thread safety and concurrent request handling
  .gitignore
  mycroft/skills/intent_services/commonqa_service.py
  ovos_core/intent_services/commonqa_service.py
  requirements/requirements.txt
  test/unittests/common_query/test_common_query.py
Labels: enhancement

#391 feat/stop_per_session
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/stop_service.py
  ovos_core/locale/de-de/global_stop.intent
  ovos_core/locale/de-de/stop.intent
  ovos_core/locale/en-us/global_stop.intent
  ovos_core/locale/en-us/stop.intent
  ovos_core/locale/es-es/stop.intent
  ovos_core/locale/fr-fr/stop.intent
  ovos_core/locale/it-it/stop.intent
  ovos_core/locale/nl-be/stop.intent
  ovos_core/locale/nl-nl/stop.intent
  ovos_core/locale/pt-pt/stop.intent
  ovos_core/locale/uk-ua/global_stop.intent
  ovos_core/locale/uk-ua/stop.intent
  test/end2end/session/test_stop.py
  test/end2end/skill-converse_test/__init__.py
  test/end2end/skill-new-stop/__init__.py
  test/end2end/skill-new-stop/locale/en-us/vocab/HelloWorldKeyword.voc
  test/end2end/skill-new-stop/setup.py
  test/end2end/skill-old-stop/__init__.py
  test/end2end/skill-old-stop/locale/en-us/vocab/HelloWorldKeyword.voc
  test/end2end/skill-old-stop/setup.py
  test/end2end/skill-ovos-hello-world/__init__.py
  test/end2end/skill-ovos-schedule/__init__.py
  test/unittests/skills/test_common_query_skill.py
Labels: enhancement, refactor

#400 Update MANIFEST.in
  MANIFEST.in
Labels: packaging

#403 fix/credentials_leaking_in_logs
  ovos_core/transformers.py
Labels: bug

#404 add "ovos.utterance.cancelled" event
  ovos_core/intent_services/__init__.py
Labels: enhancement
