Repository OpenVoiceOS/ovos-core, pull requests merged in 2024-05, with the labels that each got.

#451 fix/deactivate inside intent/converse
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/ocp_service.py
  requirements/requirements.txt
  test/end2end/routing/test_sched.py
  test/end2end/routing/test_session.py
  test/end2end/session/test_converse.py
  test/end2end/session/test_fallback.py
  test/end2end/session/test_fallback_v1.py
  test/end2end/session/test_get_response.py
  test/end2end/session/test_sched.py
  test/end2end/session/test_session.py
  test/end2end/session/test_stop.py
  test/end2end/skill-converse_test/__init__.py
  test/end2end/skill-converse_test/locale/en-us/deactivate.intent
  test/unittests/common_query/test_common_query.py
Labels: bug

#452 fix/deactivate_in_converse/fallback
  requirements/requirements.txt
  test/end2end/session/test_complete_failure.py
  test/end2end/session/test_converse.py
  test/end2end/session/test_fallback.py
  test/end2end/session/test_fallback_v1.py
  test/end2end/session/test_sched.py
  test/end2end/session/test_session.py
  test/end2end/session/test_stop.py
  test/end2end/skill-ovos-fallback-unknown/__init__.py
Labels: bug

#456 feat/legacy_audio_api
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/ocp_service.py
  ovos_core/transformers.py
  requirements/tests.txt
  test/end2end/minicroft.py
  test/end2end/session/test_ocp.py
  test/end2end/skill-fake-fm/__init__.py
  test/end2end/skill-fake-fm/setup.py
Labels: enhancement

#457 feat/legacy_common_play
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  mycroft/skills/common_play_skill.py
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/ocp_service.py
  test/end2end/session/test_ocp.py
  test/end2end/skill-fake-fm-legacy/__init__.py
  test/end2end/skill-fake-fm-legacy/setup.py
Labels: enhancement, mycroft-sync

#461 automations/translations
  .github/workflows/publish_alpha.yml
  .github/workflows/sync_tx.yml
  scripts/prepare_translations.py
  scripts/sync_translations.py
  translations/de-de/intents.json
  translations/en-us/dialogs.json
  translations/en-us/intents.json
  translations/en-us/vocabs.json
  translations/es-es/intents.json
  translations/fr-fr/intents.json
  translations/it-it/intents.json
  translations/nl-be/intents.json
  translations/nl-nl/intents.json
  translations/pt-pt/intents.json
  translations/uk-ua/intents.json
Labels: tests and automation

#477 link translations portal
  README.md
Labels: documentation

#480 fix/ocp_pipeline_config
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/ocp_service.py
Labels: bug

#481 fix/several_OCP_issues
  ovos_core/intent_services/ocp_service.py
Labels: bug

#478 feat/ovos.utterance.handled
  .github/workflows/unit_tests.yml
  mycroft/skills/common_play_skill.py
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/commonqa_service.py
  ovos_core/intent_services/converse_service.py
  ovos_core/intent_services/fallback_service.py
  ovos_core/intent_services/ocp_service.py
  ovos_core/intent_services/stop_service.py
  requirements/requirements.txt
  test/end2end/routing/test_sched.py
  test/end2end/routing/test_session.py
  test/end2end/session/test_complete_failure.py
  test/end2end/session/test_converse.py
  test/end2end/session/test_fallback.py
  test/end2end/session/test_get_response.py
  test/end2end/session/test_ocp.py
  test/end2end/session/test_sched.py
  test/end2end/session/test_session.py
  test/end2end/session/test_stop.py
  test/unittests/skills/test_intent_service.py
Labels: enhancement

#486 tests/cancel_utterance
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  ovos_core/transformers.py
  requirements/tests.txt
  test/end2end/metadata-test-plugin/metadata_test/__init__.py
  test/end2end/metadata-test-plugin/setup.py
  test/end2end/minicroft.py
  test/end2end/session/test_transformers.py
Labels: tests and automation

#485 fix/mycroft_compat
  mycroft/enclosure/__init__.py
  mycroft/enclosure/api.py
  mycroft/enclosure/display_manager.py
  mycroft/gui/__init__.py
  mycroft/gui/extensions.py
  mycroft/skills/event_scheduler.py
  mycroft/util/audio_test.py
Labels: bug, mycroft-sync

#487 Troubleshoot transformers test failures
  test/end2end/metadata-test-plugin/metadata_test/__init__.py
  test/end2end/metadata-test-plugin/setup.py
  test/end2end/session/test_transformers.py
Labels: tests and automation
