Repository OpenVoiceOS/ovos-core, pull requests merged in 2024-06, with the labels that each got.

#491 enable ocp with utils 0.0.38 compat
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/ocp_service.py
  test/end2end/minicroft.py
  test/end2end/session/test_ocp.py
  test/end2end/skill-fake-fm/__init__.py
  test/unittests/skills/test_intent_service.py
  test/unittests/skills/test_ocp.py
Labels: refactor, packaging

#494 hotfix/ensure prob is float
  ovos_core/intent_services/ocp_service.py
Labels: bug

#495 fix/ocp_per_session
  ovos_core/intent_services/ocp_service.py
  test/end2end/session/test_ocp.py
  test/unittests/skills/test_intent_service.py
Labels: bug

#497 improve common_qa/OCP conflicts
  ovos_core/intent_services/commonqa_service.py
  ovos_core/intent_services/locale/en-us/QuestionWord.voc
  ovos_core/intent_services/locale/pt-pt/QuestionWord.voc
  test/end2end/session/test_ocp.py
  test/unittests/skills/test_intent_service.py
  translations/en-us/vocabs.json
  translations/pt-pt/vocabs.json
Labels: bug

#476 polish
  translations/pl-pl/intents.json
Labels: translation

#492 feat/blacklist_from_session
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/adapt_service.py
  ovos_core/intent_services/commonqa_service.py
  ovos_core/intent_services/converse_service.py
  ovos_core/intent_services/fallback_service.py
  ovos_core/intent_services/ocp_service.py
  ovos_core/intent_services/padacioso_service.py
  ovos_core/intent_services/padatious_service.py
  ovos_core/intent_services/stop_service.py
  requirements/requirements.txt
  test/end2end/minicroft.py
  test/end2end/session/test_blacklist.py
  test/end2end/skill-ovos-fakewiki/__init__.py
  test/end2end/skill-ovos-fakewiki/setup.py
  test/unittests/skills/test_utterance_intents.py
Labels: bug, enhancement, security

#502 refactor/alt_classifier
  .github/workflows/unit_tests.yml
  ovos_core/intent_services/locale/en-us/ADKeyword.voc
  ovos_core/intent_services/locale/en-us/ASMRKeyword.voc
  ovos_core/intent_services/locale/en-us/AdultKeyword.voc
  ovos_core/intent_services/locale/en-us/AnimeKeyword.voc
  ovos_core/intent_services/locale/en-us/AudioBookKeyword.voc
  ovos_core/intent_services/locale/en-us/AudioDramaKeyword.voc
  ovos_core/intent_services/locale/en-us/AudioKeyword.voc
  ovos_core/intent_services/locale/en-us/BWKeyword.voc
  ovos_core/intent_services/locale/en-us/CartoonKeyword.voc
  ovos_core/intent_services/locale/en-us/ComicBookKeyword.voc
  ovos_core/intent_services/locale/en-us/DocumentaryKeyword.voc
  ovos_core/intent_services/locale/en-us/GameKeyword.voc
  ovos_core/intent_services/locale/en-us/HentaiKeyword.voc
  ovos_core/intent_services/locale/en-us/MovieKeyword.voc
  ovos_core/intent_services/locale/en-us/MusicKeyword.voc
  ovos_core/intent_services/locale/en-us/NewsKeyword.voc
  ovos_core/intent_services/locale/en-us/PodcastKeyword.voc
  ovos_core/intent_services/locale/en-us/RadioKeyword.voc
  ovos_core/intent_services/locale/en-us/SeriesKeyword.voc
  ovos_core/intent_services/locale/en-us/ShortKeyword.voc
  ovos_core/intent_services/locale/en-us/SilentKeyword.voc
  ovos_core/intent_services/locale/en-us/TVKeyword.voc
  ovos_core/intent_services/locale/en-us/TrailerKeyword.voc
  ovos_core/intent_services/locale/en-us/VideoKeyword.voc
  ovos_core/intent_services/ocp_service.py
  test/unittests/skills/test_ocp.py
  translations/en-us/vocabs.json
Labels: enhancement

#505 feat/more_qwords
  ovos_core/intent_services/locale/en-us/QuestionWord.voc
  ovos_core/intent_services/locale/pt-pt/QuestionWord.voc
  translations/en-us/vocabs.json
  translations/pt-pt/vocabs.json
Labels: enhancement

#506 improve_fallback_timeout
  .github/workflows/coverage.yml
  .github/workflows/unit_tests.yml
  ovos_core/intent_services/fallback_service.py
  requirements/requirements.txt
  test/end2end/session/test_fallback.py
  test/end2end/skill-ovos-slow-fallback/__init__.py
  test/end2end/skill-ovos-slow-fallback/setup.py
Labels: bug

#510 cleanup/explicit_utterance_handled_message
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/commonqa_service.py
  ovos_core/intent_services/converse_service.py
  ovos_core/intent_services/stop_service.py
Labels: refactor

#511 fix/activation_session
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/converse_service.py
  ovos_core/intent_services/ocp_service.py
  requirements/requirements.txt
  test/end2end/routing/test_sched.py
  test/end2end/routing/test_session.py
  test/end2end/session/test_blacklist.py
  test/end2end/session/test_converse.py
  test/end2end/session/test_get_response.py
  test/end2end/session/test_ocp.py
  test/end2end/session/test_sched.py
  test/end2end/session/test_session.py
  test/end2end/session/test_stop.py
Labels: bug

#513 refactor/less_patches
  ovos_core/intent_services/ocp_service.py
  requirements/requirements.txt
Labels: refactor, packaging

#514 fix/legacy_play
  ovos_core/intent_services/ocp_service.py
  requirements/requirements.txt
Labels: bug

#515 fix/adapt_config
  ovos_core/intent_services/__init__.py
  ovos_core/intent_services/adapt_service.py
  ovos_core/intent_services/ocp_service.py
  ovos_core/intent_services/padatious_service.py
Labels: bug

#517 fix/no_media_skills
  ovos_core/intent_services/locale/en-us/no.media.skills.dialog
  ovos_core/intent_services/ocp_service.py
  requirements/requirements.txt
  test/end2end/session/test_ocp.py
  translations/en-us/dialogs.json
Labels: bug
