Repository OpenVoiceOS/ovos-core, pull requests merged in 2024-03, with the labels that each got.

#424 fix: blacklisted skills
  ovos_core/skill_manager.py
Labels: bug

#426 fix: old mycroft skills loading
  ovos_core/skill_manager.py
Labels: bug

#427 refactor/reduce code complexity
  ovos_core/intent_services/__init__.py
Labels: refactor

#428 more tests for skills manager
  ovos_core/skill_manager.py
  test/unittests/skills/test_manager.py
Labels: tests and automation

#429 chore(docs): add a long description to PyPi
  setup.py
Labels: packaging

#430 add "allow_alphas" config
  ovos_core/skill_installer.py
Labels: enhancement
